### ISSUE TITLE
Validate the response

### ISSUE THREAD

**Issue by joanvila** [joanvila/raml-js-validator#9]
This should be an optional functionality for the user. Something like `--validate-response`.

Given this response:

```
responses:
      200:
        body:
          type: Task
          example: !include examples/taskResponse.json
```

We should validate that the response object matches with the Task definition.

```
types:
  Task:
    properties:
      name:
        type: string
        required: true
      owner:
        type: Person
        required: true
```

As it is shown in the Task type definition, many levels of types can be present in a response. In order allow the user to be less or more permissive, we are going to provide another option such `--deep-level` which will accept an integer and will be the number of levels that we are going to go deep inside the response in order to check the schema.
